// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct DataTest {
	float r;
	float g;
	float b;
};

RWStructuredBuffer<DataTest> dataTest;

//https://forum.unity.com/threads/solved-unity-compute-shader-cycle-through-rwstructuredbuffer.533682/
[numthreads(10,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	for (int i = 0; i < (int)dataTest.Length; i++)
	{
		dataTest[i].r = 0;
	}
}
